version: '3'

services:

  quartermaster:
    container_name: quartermaster
    image: h0d0user/quartermaster:latest
    restart: always
    environment:
      - APIKEY_SECRET_B64E=APIKEY_SECRET_B64E
      - TELE_BOT_TOKEN=TELE_BOT_TOKEN
      - TELE_CHAT_ID=TELE_CHAT_ID
    networks:
      - quartermaster_net
    volumes:
      - "./search_scheme.txt:/opt/search_scheme.txt"

networks:
  quartermaster_net: