version: '3'

services:

  quartermaster:
    container_name: quartermaster
    image: h0d0user/quartermaster:latest
    restart: always
    environment:
      - APIKEY_SECRET_B64E=APIKEY_SECRET_B64E
      - TELEGRAM_BOT_TOKEN=TELEGRAM_BOT_TOKEN
      - TELEGRAM_CHAT_ID=TELEGRAM_CHAT_ID
      - PROPERTY_TYPE=PROPERTY_TYPE
      - OPERATION=OPERATION
#      - CENTER_GCS=CENTER_GCS
      - DISTANCE=DISTANCE
      - ITEMS=ITEMS
    networks:
      - quartermaster_net
#    volumes:
#      - "./settings.txt:/opt/settings.txt"

networks:
  quartermaster_net: